[meta]
name = "Unlock Izumi"
author = "malucart"
version = "1.0.0"
desc = "Makes Izumi's route accessible without beating Izumi Cure"
icon = "icon.png"
uuid = "f3a90bd9-b426-40a6-81cb-e79fcc42b41e"

[components]
all = ["All", "main.lua"]