[meta]
name = "Okuhiko7"
author = "malucart"
desc = "Removes everything in the main story except for Okuhiko."
icon = "icon.png"
uuid = "bda76b73-4c5e-491c-839a-f2711e3fc332"

[components]
all = ["All", "main.lua"]